# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from analysis.models import FinancialConcept

def insertData(apps, schema_editor):
    root = FinancialConcept(name='Cuenta de pérdidas y ganancias consolidada', xbrl_element='ipp-gen:CuentaPerdidasGananciasConsolidada',
        taxonomy='http://www.cnmv.es/ipp/2008')
    root.save()
    concepts = [{
        'name': 'Importe neto de la cifra de negocios',
        'xbrl_element': 'ifrs-gp:RevenueTotalByNature',
    }, {
        'name': 'Variación de existencias de productos terminados y en curso de fabricación',
        'xbrl_element': 'ifrs-gp:ChangesInInventoriesOfFinishedGoodsAndWorkInProgressByNature',
    }, {
        'xbrl_element': 'ifrs-gp:WorkPerformedByEntityAndCapitalised',
        'name': 'Trabajos realizados por la empresa para su activo',
    }, {
        'xbrl_element': 'ifrs-gp:RawMaterialsAndConsumablesUsedByNature',
        'name': 'Aprovisionamientos',
    }, {
        'xbrl_element': 'ifrs-gp:OtherOperatingIncomeTotalByNature',
        'name': 'Otros ingresos de explotación',
    }, {
        'xbrl_element': 'ifrs-gp:EmployeeExpensesByNature',
        'name': 'Gastos de personal',
    }, {
        'xbrl_element': 'ifrs-gp:MiscellaneousOtherOperatingExpensesByNature',
        'name': 'Otros gastos de explotación',
    }, {
        'xbrl_element': 'ifrs-gp:DepreciationAndAmortisation',
        'name': 'Amortización del inmovilizado',
    }, {
        'xbrl_element': 'ipp-gen:ImputacionSubvencionesInmovilizadoNoFinancieroOtras',
        'name': 'Imputación de subvenciones de inmovilizado no financiero y otras',
    }, {
        'xbrl_element': 'ipp-gen:DeterioroResultadoEnajenacionesInmovilizado',
        'name': 'Deterioro y resultado por enajenaciones del inmovilizado',
    }, {
        'xbrl_element': 'ipp-gen:OtrosResultados',
        'name': 'Otros resultados',
    }, {
        'xbrl_element': 'ipp-gen:ResultadoExplotacionNiif',
        'name': 'RESULTADO DE EXPLOTACIÓN',
    }, {
        'xbrl_element': 'ipp-gen:IngresosFinancieros',
        'name': 'Ingresos financieros',
    }, {
        'xbrl_element': 'ifrs-gp:FinanceCostsForNonFinancialActivities',
        'name': 'Gastos financieros',
    }, {
        'xbrl_element': 'ipp-gen:VariacionValorRazonableInstrumentosFinancieros',
        'name': 'Variación de valor razonable en instrumentos financieros',
    }, {
        'xbrl_element': 'ifrs-gp:GainsLossesOnFinancialInstrumentsExchangeDifferenceRevaluations',
        'name': 'Diferencias de cambio',
    }, {
        'name': 'Deterioro y resultado por enajenaciones de instrumentos financieros',
        'xbrl_element': 'ipp-gen:DeterioroResultadoEnajenacionesInstrumentosFinancieros',
    }, {
        'name': 'RESULTADO FINANCIERO',
        'xbrl_element': 'ipp-gen:ResultadoFinanciero',
    }, {
        'name': 'Resultado de entidades valoradas por el método de la participación',
        'xbrl_element': 'ifrs-gp:ShareOfProfitLossFromEquityAccountedInvestments',
    }, {
        'name': 'RESULTADO ANTES DE IMPUESTOS',
        'xbrl_element': 'ipp-gen:ResultadoAntesImpuestosNiif',
    }, {
        'name': 'Impuesto sobre beneficios',
        'xbrl_element': 'ifrs-gp:IncomeTaxExpenseIncome',
    }, {
        'name': 'RESULTADO DEL EJERCICIO PROCEDENTE DE OPERACIONES CONTINUADAS',
        'xbrl_element': 'ipp-gen:ResultadoEjercicioProcedenteOperacionesContinuadasNiif',
    }, {
        'name': 'Resultado del ejercicio procedente de operaciones interrumpidas neto de impuestos',
        'xbrl_element': 'ifrs-gp:ProfitLossFromDiscontinuedOperationsNetOfTax',
    }, {
        'name': 'RESULTADO DEL EJERCICIO',
        'xbrl_element': 'ipp-gen:ResultadoEjercicioNiif',
    }, {
        'name': 'Resultado atribuido a la entidad dominante',
        'xbrl_element': 'ifrs-gp:ProfitLossAttributableToEquityHoldersOfParent',
    }, {
        'name': 'Resultado atribuido a los intereses minoritarios',
        'xbrl_element': 'ifrs-gp:ProfitLossAttributableToMinorityInterest',
    }, {
        'name': 'BENEFICIO POR ACCIÓN BÁSICO',
        'xbrl_element': 'ifrs-gp:BasicEarningsLossPerShare',
    }, {
        'name': 'BENEFICIO POR ACCIÓN DILUIDO',
        'xbrl_element': 'ifrs-gp:DilutedEarningsLossPerShare',
    }]
    for concept in concepts:
        FinancialConcept(name=concept['name'], xbrl_element=concept['xbrl_element'], parent=root, taxonomy=root.taxonomy).save()

    root = FinancialConcept(name='Balance consolidado', xbrl_element='ipp-gen:BalanceConsolidado', taxonomy='http://www.cnmv.es/ipp/2008')
    root.save()
    concepts = [{
        'xbrl_element': 'ipp-gen:ActivoNoCorrienteNiif',
        'name': 'A) ACTIVO NO CORRIENTE'
    }, {
        'xbrl_element': 'ifrs-gp:IntangibleAssetsNet',
        'name': '1. Inmovilizado intangible:'
    }, {
        'xbrl_element': 'ifrs-gp:GoodwillNet',
        'name': 'a) Fondo de comercio'
    }, {
        'xbrl_element': 'ifrs-gp:IdentifiableIntangibleAssetsNet',
        'name': 'b) Otro inmobilizado intangible'
    }, {
        'xbrl_element': 'ifrs-gp:PropertyPlantAndEquipmentNet',
        'name': '2. Inmovilizado material'
    }, {
        'xbrl_element': 'ifrs-gp:InvestmentProperty',
        'name': '3. Inversiones inmobiliarias'
    }, {
        'xbrl_element': 'ifrs-gp:EquityMethodAccountedInvestmentsTotal',
        'name': '4. Inversiones contabilizadas aplicando el método de la participación'
    }, {
        'xbrl_element': 'ifrs-gp:OtherFinancialAssetsNonCurrent',
        'name': '5. Activos financieros no corrientes'
    }, {
        'xbrl_element': 'ifrs-gp:DeferredTaxAssets',
        'name': '6. Activos por impuesto diferido'
    }, {
        'xbrl_element': 'ifrs-gp:OtherAssetsNonCurrent',
        'name': '7. Otros activos no corrientes'
    }, {
        'xbrl_element': 'ipp-gen:ActivoCorrienteNiif',
        'name': 'B) ACTIVO CORRIENTE'
    }, {
        'xbrl_element': 'ifrs-gp:NonCurrentAssetsAndDisposalGroupsHeldForSale',
        'name': '1. Activos no corrientes mantenidos para la venta'
    }, {
        'xbrl_element': 'ifrs-gp:Inventories',
        'name': '2. Existencias'
    }, {
        'xbrl_element': 'ifrs-gp:TradeAndOtherReceivablesNetCurrent',
        'name': '3. Deudores comerciales y otras cuentas a cobrar:'
    }, {
        'xbrl_element': 'ipp-gen:ClientesVentasPrestacionesServicios',
        'name': 'a) Clientes por ventas y prestaciones de servicios'
    }, {
        'xbrl_element': 'ipp-gen:OtrosDeudores',
        'name': 'b) Otros deudores'
    }, {
        'xbrl_element': 'ifrs-gp:CurrentTaxReceivables',
        'name': 'c) Activos por impuesto corriente'
    }, {
        'xbrl_element': 'ifrs-gp:OtherFinancialAssetsCurrent',
        'name': '4. Otros activos financieros corrientes'
    }, {
        'xbrl_element': 'ipp-gen:OtrosActivosCorrientes',
        'name': '5. Otros activos corrientes'
    }, {
        'xbrl_element': 'ifrs-gp:CashAndCashEquivalents',
        'name': '6. Efectivo y otros activos líquidos equivalentes'
    }, {
        'xbrl_element': 'ipp-gen:TotalActivoNiif',
        'name': 'TOTAL ACTIVO (A + B)'
    }, {
        'xbrl_element': 'ipp-gen:PatrimonioNetoNiif',
        'name': 'A) PATRIMONIO NETO (A.1 + A.2 + A.3)'
    }, {
        'xbrl_element': 'ipp-gen:FondosPropiosNiif',
        'name': 'A.1) FONDOS PROPIOS'
    }, {
        'xbrl_element': 'es-be-fs:CapitalFondoDotacion',
        'name': '1. Capital'
    }, {
        'xbrl_element': 'ifrs-gp:IssuedCapital',
        'name': 'a) Escriturado'
    }, {
        'xbrl_element': 'es-be-fs:PendienteDesembolsoNoExigido',
        'name': 'b) Menos: Capital no exigido'
    }, {
        'xbrl_element': 'ifrs-gp:SharePremiumTotal',
        'name': '2. Prima de emisión'
    }, {
        'xbrl_element': 'ifrs-gp:OtherReserves',
        'name': '3. Reservas'
    }, {
        'xbrl_element': 'ifrs-gp:TreasuryShares',
        'name': '4. Menos: Acciones y participaciones en patrimonio propias'
    }, {
        'xbrl_element': 'ipp-gen:ResultadosEjerciciosAnteriores',
        'name': '5. Resultados de ejercicios anteriores'
    }, {
        'xbrl_element': 'ipp-gen:OtrasAportacionesSocios',
        'name': '6. Otras aportaciones de socios'
    }, {
        'xbrl_element': 'es-be-fs:ResultadoAtribuidoGrupoBalance',
        'name': '7. Resultado del ejercicio atribuido a la entidad dominante'
    }, {
        'xbrl_element': 'es-be-fs:MenosDividendosRetribuciones',
        'name': '8. Menos: Dividendo a cuenta'
    }, {
        'xbrl_element': 'es-be-fs:OtrosInstrumentosCapitalFondosPropios',
        'name': '9. Otros instrumentos de patrimonio neto'
    }, {
        'xbrl_element': 'ipp-gen:AjustesValoracionNiif',
        'name': 'A.2) AJUSTES POR CAMBIOS DE VALOR'
    }, {
        'xbrl_element': 'ifrs-gp:AvailableForSaleReserves',
        'name': '1. Activos financieros disponibles para la venta'
    }, {
        'xbrl_element': 'ipp-com:OperacionesCobertura',
        'name': '2. Operaciones de cobertura'
    }, {
        'xbrl_element': 'ipp-gen:DiferenciasConversion',
        'name': '3. Diferencias de conversión'
    }, {
        'xbrl_element': 'ipp-com:OtrosAjustesValoracion',
        'name': '4. Otros'
    }, {
        'xbrl_element': 'ifrs-gp:EquityAttributableToEquityHoldersOfParent',
        'name': 'PATRIMONIO NETO ATRIBUIDO A LA ENTIDAD DOMINANTE (A.1 + A.2)'
    }, {
        'xbrl_element': 'ifrs-gp:MinorityInterest',
        'name': 'A.3) INTERESES MINORITARIOS'
    }, {
        'xbrl_element': 'ipp-gen:PasivoNoCorrienteNiif',
        'name': 'B) PASIVO NO CORRIENTE'
    }, {
        'xbrl_element': 'ifrs-gp:GovernmentGrantsNonCurrent',
        'name': '1. Subvenciones'
    }, {
        'xbrl_element': 'ifrs-gp:ProvisionsNonCurrent',
        'name': '2. Provisiones no corrientes'
    }, {
        'xbrl_element': 'ipp-gen:DeudasLargoPlazo',
        'name': '3. Pasivos financieros no corrientes'
    }, {
        'xbrl_element': 'ipp-gen:DeudasEntidadesFinancierasLargoPlazo',
        'name': 'a) Deudas con entidades de crédito y obligaciones u otros valores negociables l/p'
    }, {
        'xbrl_element': 'ifrs-gp:OtherFinancialLiabilitiesNonCurrent',
        'name': 'b) Otros pasivos financieros'
    }, {
        'xbrl_element': 'ifrs-gp:DeferredTaxLiabilities',
        'name': '4. Pasivos por impuesto diferido'
    }, {
        'xbrl_element': 'ifrs-gp:OtherLiabilitiesNonCurrent',
        'name': '5. Otros pasivos no corrientes l/p'
    }, {
        'xbrl_element': 'ipp-gen:PasivoCorrienteNiif',
        'name': 'C) PASIVO CORRIENTE'
    }, {
        'xbrl_element': 'ifrs-gp:LiabilitiesIncludedInDisposalGroupsClassifiedAsHeldForSale',
        'name': '1. Pasivos vinculados con activos no corrientes mantenidos para la venta'
    }, {
        'xbrl_element': 'ifrs-gp:ProvisionsCurrent',
        'name': '2. Provisiones corrientes'
    }, {
        'xbrl_element': 'ipp-gen:DeudasCortoPlazo',
        'name': '3. Pasivos financieros corrientes'
    }, {
        'xbrl_element': 'ipp-gen:DeudasEntidadesFinancierasCortoPlazo',
        'name': 'a) Deudas con entidades de crédito y obligaciones u otros valores negociables c/p'
    }, {
        'xbrl_element': 'ifrs-gp:OtherFinancialLiabilitiesCurrent',
        'name': 'b) Otros pasivos financieros c/p'
    }, {
        'xbrl_element': 'ipp-gen:AcreedoresComercialesOtrasCuentasPagar',
        'name': '4. Acreedores comerciales y otras cuentas a pagar:'
    }, {
        'xbrl_element': 'ifrs-gp:TradeAndOtherPayablesCurrent',
        'name': 'a) Proveedores'
    }, {
        'xbrl_element': 'ipp-gen:OtrosAcreedores',
        'name': 'b) Otros acreedores'
    }, {
        'xbrl_element': 'ifrs-gp:CurrentTaxPayables',
        'name': 'c) Pasivos por impuesto corriente'
    }, {
        'xbrl_element': 'ifrs-gp:OtherLiabilitiesCurrent',
        'name': '5. Otros pasivos corrientes'
    }, {
        'xbrl_element': 'ipp-gen:TotalPasivoPatrimonioNetoNiif',
        'name': 'TOTAL PATRIMONIO NETO Y PASIVO (A + B + C )'
    }]
    for concept in concepts:
        FinancialConcept(name=concept['name'], xbrl_element=concept['xbrl_element'], parent=root, taxonomy=root.taxonomy).save()

    root = FinancialConcept(name='Balance consolidado', taxonomy='http://www.cnmv.es/ipp/2005',
        xbrl_element='ipp-mas-pat:ResultadosGrupoConsolidadoNormasInternacionalesInformacionFinancieraAdoptadas')
    root.save()
    concepts = [{
        'xbrl_element': 'ipp-mas-pat:ImporteNetoCifraNegocioNIIF',
        'name': 'Importe neto de la cifra de negocio',
    },{ 
        'xbrl_element': 'ipp-mas-pat:OtrosIngresosNIIF',
        'name': 'Otros ingresos',
    },{ 
        'xbrl_element': 'ipp-mas-pat:VariacionExistenciasProductosTerminadosOEnCursoNIIF',
        'name': 'Variación de existencias de productos terminados o en curso',
    },{ 
        'xbrl_element': 'ipp-mas-pat:Aprovisionamientos',
        'name': 'Aprovisionamientos',
    },{ 
        'xbrl_element': 'ipp-mas-pat:GastoPersonalNIIF',
        'name': 'Gastos de personal',
    },{ 
        'xbrl_element': 'ipp-mas-pat:DotacionAmortizacion',
        'name': 'Dotación a la amortización',
    },{ 
        'xbrl_element': 'ipp-mas-pat:OtrosGastos',
        'name': 'Otros Gastos',
    },{ 
        'xbrl_element': 'ipp-mas-pat:BeneficioPerdidaExplotacion',
        'name': 'BENEFICIO/(PÉRDIDA) DE EXPLOTACIÓN',
    },{ 
        'xbrl_element': 'ipp-mas-pat:IngresosFinancierosNIIF',
        'name': 'Ingresos financieros',
    },{ 
        'xbrl_element': 'ipp-mas-pat:GastosFinancierosNIIF',
        'name': 'Gastos financieros',
    },{ 
        'xbrl_element': 'ipp-mas-pat:DiferenciasCambioNeto',
        'name': 'Diferencias de cambio (neto)',
    },{ 
        'xbrl_element': 'ipp-mas-pat:ResultadoVariacionesValorInstrumentosFinancierosValorRazonableNeto',
        'name': 'Resultado por variaciones de valor de instrumentos financieros a valor razonable (neto)',
    },{ 
        'xbrl_element': 'ipp-mas-pat:ResultadoVariacionesValorActivosNoFinancierosValorRazonableNeto',
        'name': 'Resultado por variaciones de valor de activos no financieros a valor razonable (neto)',
    },{ 
        'xbrl_element': 'ipp-gen-con:ResultadoDeterioroReversionDeterioroActivosNeto',
        'name': 'Resultado por deterioro/ reversión del deterioro de activos (neto)',
    },{ 
        'xbrl_element': 'ipp-mas-pat:ParticipacionResultadoEjercicioAsociadasNegociosConjuntosContabilicenSegunMetodoParticipacion',
        'name': 'Participación en el resultado del ejercicio de las asociadas y negocios conjuntos que se contabilicen según el método de la participación',
    },{ 
        'xbrl_element': 'ipp-mas-pat:ResultadoEnajenacionActivosNoCorrientesValoracionActivosNoCorrientesClasificadosComoMantenidosParaVentaNoIncluidosDentroActividadesInterrumpidasNeto',
        'name': 'Resultado de la enajenación de activos no corrientes o valoración de activos no corrientes clasificados como mantenidos para la venta no incluidos dentro de las actividades interrumpidas (neto)',
    },{ 
        'xbrl_element': 'ipp-mas-pat:OtrasGananciasPerdidasNeto',
        'name': 'Otras ganancias o pérdidas (neto)',
    },{ 
        'xbrl_element': 'ipp-mas-pat:BeneficioPerdidaAntesImpuestosActividadesContinuadas',
        'name': 'BENEFICIO/(PÉRDIDA) ANTES DE IMPUESTOS DE ACTIVIDADES CONTINUADAS',
    },{ 
        'xbrl_element': 'ipp-mas-pat:GastoImpuestoSobreGanancias',
        'name': 'Gasto por impuesto sobre las ganancias',
    },{ 
        'xbrl_element': 'ipp-mas-pat:BeneficioPerdidaEjercicioActividadesContinuadas',
        'name': 'BENEFICIO/(PÉRDIDA) DEL EJERCICIO DE ACTIVIDADES CONTINUADAS',
    },{ 
        'xbrl_element': 'ipp-mas-pat:ResultadoDespuesImpuestosActividadesInterrumpidasNeto',
        'name': 'Resultado después de impuestos de las actividades interrumpidas (neto)',
    },{ 
        'xbrl_element': 'ipp-mas-pat:BeneficioPerdidaEjercicio',
        'name': 'BENEFICIO/(PÉRDIDA) DEL EJERCICIO',
    },{ 
        'xbrl_element': 'ipp-mas-pat:InteresesMinoritariosResultado',
        'name': 'Intereses Minoritarios',
    },{ 
        'xbrl_element': 'ipp-mas-pat:BeneficioPerdidaAtribuibleTenedoresInstrumentosPatrimonioNetoDominante',
        'name': 'BENEFICIO/(PÉRDIDA) ATRIBUIBLE A TENEDORES DE INSTRUMENTOS DE PATRIMONIO NETO DE LA DOMINANTE',
    }]
    for concept in concepts:
        FinancialConcept(name=concept['name'], xbrl_element=concept['xbrl_element'], parent=root, taxonomy=root.taxonomy).save()

class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]
    concepts = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('xbrl_element', models.CharField(max_length=256, unique=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.FinancialConcept')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=4)),
                ('period', models.CharField(max_length=8)),
                ('period_begin', models.DateField()),
                ('period_end', models.DateField()),
                ('fiscal_year', models.IntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FinancialConcept')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FinancialContext')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='financialconcept',
            unique_together=set([('name', 'taxonomy')]),
        ),
        migrations.AlterUniqueTogether(
            name='financialfact',
            unique_together=set([('concept', 'context')]),
        ),
        migrations.AlterUniqueTogether(
            name='financialcontext',
            unique_together=set([('symbol', 'period_begin', 'period_end')]),
        ),
        migrations.RunPython(insertData, lambda *args: None),
    ]
