# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('html_above', models.TextField(blank=True)),
                ('lang_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Lang')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together=set([('lang_code', 'slug')]),
        ),
    ]
