# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 11:34
from __future__ import unicode_literals

from django.db import migrations, models
from analysis.models import Symbol

def insertData(apps, schema_editor):
    symbol = Symbol.objects.get(ticker='map')
    symbol.quantmod_ticker = 'map.mc'
    symbol.quantmod_lastsplit_date = '2006-10-28'
    symbol.quantmod_lastsplit_ratio = 0.2
    symbol.save()
    symbol = Symbol.objects.get(ticker='tef')
    symbol.quantmod_ticker = 'tef.mc'
    symbol.save()
    symbol = Symbol.objects.get(ticker='rep')
    symbol.quantmod_ticker = 'rep.mc'
    symbol.quantmod_lastsplit_date = '2013-06-20'
    symbol.quantmod_lastsplit_ratio = 0.974359
    symbol.save()
    symbol = Symbol.objects.get(ticker='ibex35')
    symbol.quantmod_ticker = '^ibex'
    symbol.save()

class Migration(migrations.Migration):

    replaces = [('analysis', '0003_symbol_quantmod_ticker'), ('analysis', '0004_auto_20170725_1131')]

    dependencies = [
        ('analysis', '0002_auto_20170724_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='quantmod_ticker',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='quantmod_lastsplit_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='quantmod_lastsplit_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.RunPython(insertData, lambda *args: None),
    ]
