# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20170807_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('1D', '1 Day'), ('1W', '1 Week'), ('1M', '1 Month'), ('3M', '3 Months'), ('6M', '6 Months'), ('YTD', 'Year to date'), ('1Y', '1 Year')], max_length=24)),
                ('period_return', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Symbol')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='financialconcept',
            unique_together=set([('taxonomy', 'xbrl_element')]),
        ),
    ]
