# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20170819_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='lib',
            field=models.CharField(default='dygraphs', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='financialconcept',
            unique_together=set([('taxonomy', 'xbrl_element'), ('taxonomy', 'name'), ('parent', 'xbrl_element')]),
        ),
    ]
