# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20170903_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolquote',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
