# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_symbolquote_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.Sector')),
            ],
        ),
        migrations.AddField(
            model_name='symbol',
            name='isin',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.Sector'),
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together=set([('name', 'parent')]),
        ),
    ]
