# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20170913_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcontext',
            name='period',
            field=models.CharField(choices=[('first quarter', 'First Quarter'), ('second quarter', 'Second Quarter'), ('third quarter', 'Third Quarter'), ('fourth quarter', 'Fourth Quarter'), ('first semester', 'First Semester'), ('second semester', 'Second Semester'), ('full year', 'Full Year')], default='S1', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialcontext',
            name='reporting_year',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialcontext',
            name='year',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='financialcontext',
            unique_together=set([('symbol', 'period_begin', 'period_end', 'report_type', 'reporting_year')]),
        ),
    ]
