# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 15:54
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20170917_1308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialconcept',
            unique_together=set([('taxonomy', 'xbrl_element', 'parent')]),
        ),
    ]
