# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 16:50
from __future__ import unicode_literals

from django.db import migrations
from analysis.models import FinancialConcept

def insertData(apps, schema_editor):
    concepts = [{
        'name': 'A) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE EXPLOTACION (1 + 2 + 3 + 4)',
        'xbrl_element': 'ipp-gen:FlujosEfectivoActividadesExplotacionIndirectoNiif'
    }, {
        'name': '1. Resultado antes de impuestos',
        'xbrl_element': 'ifrs-gp:ProfitLossBeforeTax'
    }, {
        'name': '2. Ajustes del resultado:',
        'xbrl_element': 'ipp-gen:AjustesResultadoFlujosEfectivoActividadesExplotacion'
    }, {
        'name': ' Amortizacion y depreciación del inmovilizado',
        'xbrl_element': 'ifrs-gp:DepreciationAndAmortisation'
    }, {
        'name': ' Otros ajustes del resultado (netos)',
        'xbrl_element': 'ipp-com:OtrosAjustes'
    }, {
        'name': '3. Cambios en el capital corriente',
        'xbrl_element': 'ifrs-gp:IncreaseDecreaseInWorkingCapitalNet'
    }, {
        'name': '4. Otros flujos de efectivo de las actividades de explotacion:',
        'xbrl_element': 'ipp-gen:OtrosFlujosEfectivoActividadesExplotacionIndirectoNiif'
    }, {
        'name': ' Pagos de interes',
        'xbrl_element': 'ifrs-gp:PaymentsOfInterestClassifiedAsOperating'
    }, {
        'name': ' Pago por dividendos y remuneraciones de otros instrumentos de patrimonio',
        'xbrl_element': 'ifrs-gp:PaymentsOfDividendsClassifiedAsOperating'
    }, {
        'name': ' Cobros de dividendos',
        'xbrl_element': 'ifrs-gp:ProceedsFromDividendsReceivedClassifiedAsOperating'
    }, {
        'name': ' Cobros de intereses',
        'xbrl_element': 'ifrs-gp:ProceedsFromInterestReceivedClassifiedAsOperating'
    }, {
        'name': ' Cobros / (pagos) por impuestos sobre beneficios',
        'xbrl_element': 'ipp-com:CobrosPagosImpuestoSobreBeneficios'
    }, {
        'name': ' Otros cobros / (pagos) de actividades de explotacion',
        'xbrl_element': 'ifrs-gp:OtherInflowsOutflowsFromOtherOperatingActivities'
    }, {
        'name': 'B) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE INVERSION (1 + 2 + 3)',
        'xbrl_element': 'ipp-gen:FlujosEfectivoActividadesInversionIndirectoNiif'
    }, {
        'name': '1. Pagos por inversiones:',
        'xbrl_element': 'es-be-fs:InversionesFlujosEfectivoActividadesInversion'
    }, {
        'name': ' Empresas del grupo y asociadas y unidades de negocio',
        'xbrl_element': 'ipp-gen:EmpresasGrupoAsociadasPagos'
    }, {
        'name': ' Inmovilizado material, intangible e inversiones inmobiliarias',
        'xbrl_element': 'ipp-gen:InmovilizadoMaterialIntangibleInversionesInmobiliariasPagos'
    }, {
        'name': ' Otros activos financieros',
        'xbrl_element': 'ipp-gen:ActivosFinancierosPagos'
    }, {
        'name': ' Otros activos',
        'xbrl_element': 'ipp-gen:OtrosActivosPagos'
    }, {
        'name': '2. Cobros por desinversiones:',
        'xbrl_element': 'es-be-fs:DesinversionesFlujosEfectivoActividadesInversion'
    }, {
        'name': ' Empresas del grupo y asociadas y unidades de negocio',
        'xbrl_element': 'es-be-fs:EntidadesGrupoMultigrupoAsociadasDesinversiones'
    }, {
        'name': ' Inmovilizado material, intangible e inversiones inmobiliarias',
        'xbrl_element': 'ipp-gen:InmovilizadoMaterialIntangibleInversionesInmobiliariasCobros'
    }, {
        'name': ' Otros activos financieros',
        'xbrl_element': 'ipp-gen:ActivosFinancierosCobros'
    }, {
        'name': ' Otros activos',
        'xbrl_element': 'ipp-gen:OtrosActivosCobros'
    }, {
        'name': '3. Otros flujos de efectivo de las actividades de inversión:',
        'xbrl_element': 'ipp-gen:OtrosFlujosEfectivoActividadesInversionTotalIndirecto'
    }, {
        'name': ' Cobros de dividendos',
        'xbrl_element': 'ifrs-gp:ProceedsFromDividendsReceivedClassifiedAsInvesting'
    }, {
        'name': ' Cobros de intereses',
        'xbrl_element': 'ifrs-gp:ProceedsFromInterestReceivedClassifiedAsInvesting'
    }, {
        'name': ' Otros cobros / (pagos) de actividades de inversión',
        'xbrl_element': 'ifrs-gp:OtherCashFlowsFromUsedInInvestingActivities'
    }, {
        'name': 'C) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE FINANCIACION (1 + 2 + 3 + 4)',
        'xbrl_element': 'ipp-gen:FlujosEfectivoActividadesFinanciacionIndirectoNiif'
    }, {
        'name': '1. Cobros y (pagos) por instrumentos de patrimonio:',
        'xbrl_element': 'ipp-gen:CobrosPagosInstrumentosPatrimonioIndirectoNiif'
    }, {
        'name': ' Emisión',
        'xbrl_element': 'ifrs-gp:ProceedsFromIssuanceOfEquityInstruments'
    }, {
        'name': ' Amortización',
        'xbrl_element': 'ifrs-gp:RepurchaseOfEquityInstrumentsSubsequentlyCancelled'
    }, {
        'name': ' Adquisición',
        'xbrl_element': 'ifrs-gp:PurchaseOfTreasuryShares'
    }, {
        'name': ' Enajenación',
        'xbrl_element': 'ifrs-gp:ProceedsFromIssuanceOfTreasuryShares'
    }, {
        'name': '2. Cobros y (pagos) por instrumentos de pasivo financiero:',
        'xbrl_element': 'ipp-gen:CobrosPagosInstrumentosPasivoFinanciero'
    }, {
        'name': ' Emisión',
        'xbrl_element': 'ipp-gen:EmisionPasivoFinanciero'
    }, {
        'name': ' Devolución y amortización',
        'xbrl_element': 'ipp-gen:DevolucionAmortizacion'
    }, {
        'name': '3. Pagos por dividendos y remuneraciones de otros instrumentos de patrimonio',
        'xbrl_element': 'ifrs-gp:PaymentsOfDividendsClassifiedAsFinancing'
    }, {
        'name': '4. Otros flujos de efectivo de actividades de financiación',
        'xbrl_element': 'ipp-gen:OtrosFlujosEfectivoActividadesFinanciacionIndirecto'
    }, {
        'name': ' Pagos de intereses',
        'xbrl_element': 'ifrs-gp:PaymentsOfInterestClassifiedAsFinancing'
    }, {
        'name': ' Otros cobros / (pagos) de actividades de financiación',
        'xbrl_element': 'ifrs-gp:OtherCashFlowsFromUsedInFinancingActivities'
    }, {
        'name': 'D) EFECTO DE LAS VARIACIONES DE LOS TIPOS DE CAMBIO',
        'xbrl_element': 'ifrs-gp:EffectOfExchangeRateChangesOnCashAndCashEquivalents'
    }, {
        'name': 'E) AUMENTO / (DISMINUCIÓN) NETO DE EFECTIVO Y EQUIVALENTES (A + B + C)',
        'xbrl_element': 'ipp-gen:AumentoDisminucionNetoEfectivoEquivalentesIndirectoNiif'
    }, {
        'name': 'F) EFECTIVO Y EQUIVALENTES AL COMIENZO DEL EJERCICIO',
        'xbrl_element': 'ipp-com:EfectivoEquivalentesEfectivoComienzoEjercicio'
    }, {
        'name': 'G) EFECTIVO Y EQUIVALENTE AL FINAL DEL EJERCICIO (E + F)',
        'xbrl_element': 'ipp-gen:EfectivoEquivalentesEfectivoFinalEjercicioIndirectoNiif'
    }, {
        'name': ' Caja y bancos',
        'xbrl_element': 'ipp-com:CajaBancos'
    }, {
        'name': ' Otros activos financieros',
        'xbrl_element': 'ipp-com:OtrosActivosFinancieros'
    }, {
        'name': ' Menos: descubiertos bancarios reintegrables a la vista',
        'xbrl_element': 'ipp-com:MenosDescubiertosBancariosReintegrablesVista'
    }, {
        'name': 'TOTAL EFECTIVO Y EQUIVALENTES AL FINAL DEL PERIODO',
        'xbrl_element': 'ipp-com:TotalEfectivosEquivalentesFinalPeriodo'
    }]
    root = FinancialConcept(name='Flujo de caja consolidado', xbrl_element='ipp-gen:EstadoFlujosEfectivoConsolidadoMetodoIndirecto',
        taxonomy='http://www.cnmv.es/ipp-gen/2008')
    root.save()
    root.parent = root
    root.save()
    for concept in concepts:
        FinancialConcept(name=concept['name'], xbrl_element=concept['xbrl_element'], parent=root, taxonomy=root.taxonomy).save()

    concepts = [{
        'xbrl_element': 'ipp-enc:FlujosEfectivoNetosActividadesExplotacionNiif',
        'name': 'A) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE EXPLOTACIÓN (1 + 2 + 3 + 4)'
    }, {
        'xbrl_element': 'es-be-fs:ResultadoEjercicioPatrimonioNeto',
        'name': '1. Resultado del ejercicio'
    }, {
        'xbrl_element': 'ipp-enc:AjustesParaObtenerFlujosEfectivoActividadesExplotacion',
        'name': '2. Ajustes para obtener los flujos de efectivo de las actividades de explotación:'
    }, {
        'xbrl_element': 'ifrs-gp:DepreciationAndAmortisation',
        'name': ' Amortización'
    }, {
        'xbrl_element': 'ipp-com:OtrosAjustes',
        'name': ' Otros ajustes'
    }, {
        'xbrl_element': 'ifrs-gp:IncreaseDecreaseInWorkingCapitalNet',
        'name': '3. Aumento/(Disminución) neto de los activos y pasivos de explotación:'
    }, {
        'xbrl_element': 'es-be-fs:AumentoDisminucionNetaActivosExplotacion',
        'name': ' Activos de explotación'
    }, {
        'xbrl_element': 'es-be-fs:AumentoDisminucionNetaPasivosExplotacion',
        'name': ' Pasivos de explotación'
    }, {
        'xbrl_element': 'ipp-com:CobrosPagosImpuestoSobreBeneficios',
        'name': '4. Cobros/(Pagos) por impuesto sobre beneficios'
    }, {
        'xbrl_element': 'ipp-enc:FlujosEfectivoNetosActividadesInversionNiif',
        'name': 'B) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE INVERSIÓN (1 + 2)'
    }, {
        'xbrl_element': 'ipp-enc:PagosFlujosEfectivoNetosActividadesInversionNiif',
        'name': '1. Pagos'
    }, {
        'xbrl_element': 'ifrs-gp:PaymentsToAcquirePropertyPlantAndEquipment',
        'name': ' Activos materiales'
    }, {
        'xbrl_element': 'ifrs-gp:PaymentsToAcquireIntangibleAssets',
        'name': ' Activos intangibles'
    }, {
        'xbrl_element': 'ipp-enc:ParticipacionesFlujosEfectivoActividadesInversion',
        'name': ' Participaciones'
    }, {
        'xbrl_element': 'ipp-enc:EntidadesDependientesOtrasUnidadesNegocioPagos',
        'name': ' Otras unidades de negocio'
    }, {
        'xbrl_element': 'ifrs-gp:PaymentsToAcquireNonCurrentAssetsAndDisposalGroupsHeldForSaleAndDiscontinuedOperations',
        'name': ' Activos no corrientes y pasivos asociados en venta'
    }, {
        'xbrl_element': 'ifrs-gp:PaymentsToAcquireHeldToMaturityInvestments',
        'name': ' Cartera de inversión a vencimiento'
    }, {
        'xbrl_element': 'ifrs-gp:PaymentsToAcquireOtherAssets',
        'name': ' Otros pagos relacionados con actividades de inversión'
    }, {
        'xbrl_element': 'ipp-enc:CobrosFlujosEfectivoNetosActividadesInversionNiif',
        'name': '2. Cobros'
    }, {
        'xbrl_element': 'es-be-fs:ActivosMaterialesDesinversiones',
        'name': ' Activos materiales'
    }, {
        'xbrl_element': 'ifrs-gp:ProceedsFromDisposalOfIntangibleAssets',
        'name': ' Activos intangibles'
    }, {
        'xbrl_element': 'es-be-fs:EntidadesGrupoMultigrupoAsociadasDesinversiones',
        'name': ' Participaciones'
    }, {
        'xbrl_element': 'ipp-enc:EntidadesDependientesOtrasUnidadesNegocioCobros',
        'name': ' Otras unidades de negocio'
    }, {
        'xbrl_element': 'ifrs-gp:ProceedsFromDisposalOfNonCurrentAssetsHeldForSaleAndDiscontinuedOperations',
        'name': ' Activos no corrientes y pasivos asociados en venta'
    }, {
        'xbrl_element': 'ifrs-gp:ProceedsFromDisposalOfHeldToMaturityInvestments',
        'name': ' Cartera de inversión a vencimiento'
    }, {
        'xbrl_element': 'ifrs-gp:ProceedsFromDisposalOfOtherAssets',
        'name': ' Otros cobros relacionados con actividades de inversión'
    }, {
        'xbrl_element': 'es-be-fs:TotalFlujosEfectivoNetoActividadesFinanciacion',
        'name': 'C) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE FINANCIACIÓN (1 +2)'
    }, {
        'xbrl_element': 'es-be-fs:PagosFlujosEfectivosActividadesFinanciacion',
        'name': '1.Pagos'
    }, {
        'xbrl_element': 'ifrs-gp:PaymentsOfDividendsClassifiedAsFinancing',
        'name': ' Dividendos'
    }, {
        'xbrl_element': 'ifrs-gp:RepaymentOfSubordinatedLiabilities',
        'name': ' Pasivos subordinados'
    }, {
        'xbrl_element': 'ifrs-gp:RepurchaseOfEquityInstrumentsSubsequentlyCancelled',
        'name': ' Amortización de instrumentos de capital propio'
    }, {
        'xbrl_element': 'ifrs-gp:PurchaseOfTreasuryShares',
        'name': ' Adquisicion de instrumentos de capital propio'
    }, {
        'xbrl_element': 'ipp-com:OtrosPagosRelacionadosActividadesFinanciacion',
        'name': ' Otros pagos relacionados con actividades de financiación'
    }, {
        'xbrl_element': 'ipp-com:CobrosFlujosEfectivosActividadesFinanciacion',
        'name': '2. Cobros'
    }, {
        'xbrl_element': 'ifrs-gp:ProceedsFromSubordinatedLiabilities',
        'name': ' Pasivos subordinados'
    }, {
        'xbrl_element': 'ifrs-gp:ProceedsFromIssuanceOfEquityInstruments',
        'name': ' Emisión de instrumentos de capital propio'
    }, {
        'xbrl_element': 'ifrs-gp:ProceedsFromIssuanceOfTreasuryShares',
        'name': ' Enajenación de instrumentos de capital propio'
    }, {
        'xbrl_element': 'ipp-com:OtrosCobrosRelacionadosActividadesFinanciacion',
        'name': ' Otros cobros relacionados con actividades de financiación'
    }, {
        'xbrl_element': 'ifrs-gp:EffectOfExchangeRateChangesOnCashAndCashEquivalents',
        'name': 'D) EFECTO DE LAS VARIACIONES DE LOS TIPOS DE CAMBIO'
    }, {
        'xbrl_element': 'ipp-enc:AumentoDisminucionEfectivoEquivalentesNiif',
        'name': 'E) AUMENTO (DISMINUCIÓN) NETO DEL EFECTIVO Y EQUIVALENTES (A + B +C + D)'
    }, {
        'xbrl_element': 'ipp-com:EfectivoEquivalentesEfectivoComienzoEjercicio',
        'name': 'F) EFECTIVO Y EQUIVALENTES AL INICIO DEL PERIODO'
    }, {
        'xbrl_element': 'ipp-enc:EfectivoEquivalentesFinalPeriodoNiif',
        'name': 'G) EFECTIVO Y EQUIVALENTES AL FINAL DEL PERIODO (E + F)'
    }, {
        'xbrl_element': 'ipp-enc:Caja',
        'name': ' Caja'
    }, {
        'xbrl_element': 'ipp-enc:SaldosEquivalentesEfectivoBancosCentrales',
        'name': ' Saldos equivalentes al efectivo en bancos centrales'
    }, {
        'xbrl_element': 'ipp-com:OtrosActivosFinancieros',
        'name': ' Otros activos financieros'
    }, {
        'xbrl_element': 'ipp-com:MenosDescubiertosBancariosReintegrablesVista',
        'name': ' Menos: Descubiertos bancarios reintegrables a la vista'
    }, {
        'xbrl_element': 'ipp-com:TotalEfectivosEquivalentesFinalPeriodo',
        'name': 'TOTAL EFECTIVO Y EQUIVALENTES AL FINAL DEL PERIODO'
    }]
    root = FinancialConcept(name='Flujo de caja consolidado', xbrl_element='ipp-enc:EstadoFlujosEfectivoConsolidadoMetodoIndirecto',
        taxonomy='http://www.cnmv.es/ipp-enc/2008')
    root.save()
    root.parent = root
    root.save()
    for concept in concepts:
        FinancialConcept(name=concept['name'], xbrl_element=concept['xbrl_element'], parent=root, taxonomy=root.taxonomy).save()

    concepts = [{
        'xbrl_element': 'ipp-seg:FlujosEfectivoNetosActividadesExplotacionDirecto',
        'name': 'A) FLUJOS DE EFECTIVO NETOS DE LAS ACTIVIDADES DE EXPLOTACIÓN (1 + 2 + 3)'
    }, {
        'xbrl_element': 'ipp-seg:ActividadAseguradoraDirecto',
        'name': '1. Actividad reaseguradora:'
    }, { 
        'xbrl_element': 'ipp-seg:CobrosEfectivoActividadAseguradoraDirecto',
        'name': ' Cobros en efectivo de la actividad aseguradora'
    }, { 
        'xbrl_element': 'ipp-seg:PagosEfectivoActividadAseguradoraDirecto',
        'name': ' Pagos en efectivo'
    }, { 
        'xbrl_element': 'ipp-seg:OtrasActividadesExplotacionDirecto',
        'name': '2. Otras actividades de explotación:'
    }, { 
        'xbrl_element': 'ipp-seg:CobrosEfectivoOtrasActividadesExplotacionDirecto',
        'name': ' Cobros en efectivo de otras actividades de explotación'
    }, { 
        'xbrl_element': 'ipp-seg:PagosEfectivoOtrasActividadesExplotacionDirecto',
        'name': ' Pagos en efectivo de otras actividades de explotación'
    }, { 
        'xbrl_element': 'ipp-seg:CobrosPagosImpuestoBeneficiosDirecto',
        'name': '3. Cobros/(Pagos) por impuesto sobre beneficios'
    }, { 
        'xbrl_element': 'ipp-seg:FlujosEfectivoNetosActividadesInversionDirectoNiif',
        'name': 'B) FLUJOS DE EFECTIVO NETOS DE LAS ACTIVIDADES DE INVERSIÓN (1 + 2)'
    }, { 
        'xbrl_element': 'ipp-seg:CobrosActividadesInversionDirectoNiif',
        'name': '1. Cobros de actividades de inversión:'
    }, { 
        'xbrl_element': 'ipp-seg:InmovilizadoMaterialCobrosDirecto',
        'name': ' Inmovilizado material'
    }, { 
        'xbrl_element': 'ipp-seg:InversionesInmobiliariasCobrosDirecto',
        'name': ' Inversiones inmobiliarias'
    }, { 
        'xbrl_element': 'ipp-seg:InmovilizadoIntangibleCobrosDirecto',
        'name': ' Inmovilizado intangible'
    }, { 
        'xbrl_element': 'ipp-seg:InstrumentosFinancierosCobrosDirecto',
        'name': ' Instrumentos financieros'
    }, { 
        'xbrl_element': 'ipp-seg:ParticipacionesCobrosDirecto',
        'name': ' Participaciones'
    }, { 
        'xbrl_element': 'ipp-seg:EntidadesDependientesOtrasUnidadesNegocioCobrosDirecto',
        'name': ' Otras unidades de negocio'
    }, { 
        'xbrl_element': 'ipp-seg:InteresesCobradosDirecto',
        'name': ' Intereses cobrados'
    }, { 
        'xbrl_element': 'ipp-seg:DividendosCobradosDirecto',
        'name': ' Dividendos cobrados'
    }, { 
        'xbrl_element': 'ipp-seg:OtrosCobrosRelacionadosActividadesInversionDirecto',
        'name': ' Otros cobros relacionados con actividades de inversión'
    }, { 
        'xbrl_element': 'ipp-seg:PagosActividadesInversionDirectoNiif',
        'name': '2. Pagos de actividades de inversión:'
    }, { 
        'xbrl_element': 'ipp-seg:InmovilizadoMaterialPagosDirecto',
        'name': ' Inmovilizado material'
    }, { 
        'xbrl_element': 'ipp-seg:InversionesInmobiliariasPagosDirecto',
        'name': ' Inversiones inmobiliarias'
    }, { 
        'xbrl_element': 'ipp-seg:InmovilizadoIntangiblePagosDirecto',
        'name': ' Inmovilizado intangible'
    }, { 
        'xbrl_element': 'ipp-seg:InstrumentosFinancierosPagosDirecto',
        'name': ' Instrumentos financieros'
    }, { 
        'xbrl_element': 'ipp-seg:ParticipacionesPagosDirecto',
        'name': ' Participaciones'
    }, { 
        'xbrl_element': 'ipp-seg:EntidadesDependientesOtrasUnidadesNegocioPagosDirecto',
        'name': ' Otras unidades de negocio'
    }, { 
        'xbrl_element': 'ipp-seg:OtrosPagosRelacionadosActividadesInversionDirecto',
        'name': ' Otros pagos relacionados con actividades de inversión'
    }, { 
        'xbrl_element': 'ipp-seg:FlujosEfectivoNetosActividadesFinanciacionDirecto',
        'name': 'C) FLUJOS DE EFECTIVO NETOS DE LAS ACTIVIDADES DE FINANCIACIÓN (1 + 2)'
    }, { 
        'xbrl_element': 'ipp-seg:CobrosActividadesFinanciacionDirecto',
        'name': '1. Cobros de actividades de financiación'
    }, { 
        'xbrl_element': 'ipp-seg:PasivosSubordinadosCobrosDirecto',
        'name': ' Pasivos subordinados'
    }, { 
        'xbrl_element': 'ipp-seg:CobrosEmisionInstrumentosPatrimonioAmpliacionCapitalDirecto',
        'name': ' Cobros por emisión de instrumentos de patrimonio y ampliación de capital'
    }, { 
        'xbrl_element': 'ipp-seg:DerramasActivasAportacionesSociosMutualistasDirecto',
        'name': ' Derramas activas y aportaciones de los socios o mutualistas'
    }, { 
        'xbrl_element': 'ipp-seg:EnajenacionValoresPropiosDirecto',
        'name': ' Enajenación de valores propios'
    }, { 
        'xbrl_element': 'ipp-seg:OtrosCobrosRelacionadosActividadesFinanciacionDirecto',
        'name': ' Otros cobros relacionados con actividades de financiación'
    }, { 
        'xbrl_element': 'ipp-seg:PagosActividadesFinanciacionDirecto',
        'name': '2. Pagos de actividades de financiación'
    }, { 
        'xbrl_element': 'ipp-seg:DividendosAccionistasDirecto',
        'name': ' Dividendos a los accionistas'
    }, { 
        'xbrl_element': 'ipp-seg:InteresesPagadosDirecto',
        'name': ' Intereses pagados'
    }, { 
        'xbrl_element': 'ipp-seg:PasivosSubordinadosPagosDirecto',
        'name': ' Pasivos subordinados'
    }, { 
        'xbrl_element': 'ipp-seg:PagosDevolucionAportacionesAccionistasDirecto',
        'name': ' Pago por devolución de aportaciones a los accionistas'
    }, { 
        'xbrl_element': 'ipp-seg:DerramasPasivasDevolucionAportacionesSociosMutualistasDirecto',
        'name': ' Derramas pasivas y devolución de aportaciones a los socios y mutualistas'
    }, { 
        'xbrl_element': 'ipp-seg:AdquisicionValoresPropiosDirecto',
        'name': ' Adquisición de valores propios'
    }, { 
        'xbrl_element': 'ipp-seg:OtrosPagosRelacionadosActividadesFinanciacionDirecto',
        'name': ' Otros pagos relacionados con actividades de financiación'
    }, { 
        'xbrl_element': 'ipp-seg:EfectoVariacionTipoCambioDirecto',
        'name': 'D) EFECTO DE LA VARIACIÓN DEL TIPO DE CAMBIO'
    }, { 
        'xbrl_element': 'ipp-seg:AumentoDisminucionEfectivoEquivalentesDirectoNiif',
        'name': 'E) AUMENTO/(DISMINUCIÓN) DE EFECTIVO Y EQUIVALENTES (A + B + C + D)'
    }, { 
        'xbrl_element': 'ipp-seg:EfectivoEquivalentesComienzoPeriodoDirecto',
        'name': 'F) EFECTIVO Y EQUIVALENTES AL COMIENZO DEL PERIODO'
    }, { 
        'xbrl_element': 'ipp-seg:EfectivoEquivalentesFinalPeriodoDirectoNiif',
        'name': 'G) EFECTIVO Y EQUIVALENTES AL FINAL DEL PERIODO (E + F)'
    }, { 
        'xbrl_element': 'ipp-seg:CajaBancosDirecto',
        'name': ' Caja y bancos'
    }, { 
        'xbrl_element': 'ipp-seg:OtrosActivosFinancierosDirecto',
        'name': ' Otros activos financieros'
    }, { 
        'xbrl_element': 'ipp-seg:DescubiertosBancariosReintegrablesVistaDirecto',
        'name': ' Menos: Descubiertos bancarios reintegrables a la vista'
    }, { 
        'xbrl_element': 'ipp-seg:TotalEfectivoEquivalentesEfectivoFinalPeriodoDirecto',
        'name': 'TOTAL EFECTIVO Y EQUIVALENTES AL FINAL DEL PERIODO'
    }]
    root = FinancialConcept(name='Flujo de caja consolidado', xbrl_element='ipp-seg:EstadoFlujosEfectivoConsolidadoMetodoIndirecto',
        taxonomy='http://www.cnmv.es/ipp-seg/2008')
    root.save()
    root.parent = root
    root.save()
    for concept in concepts:
        FinancialConcept(name=concept['name'], xbrl_element=concept['xbrl_element'], parent=root, taxonomy=root.taxonomy).save()

    concepts = [{
        'xbrl_element': 'ipp_ge:EstadoFlujosEfectivoConsolidadoMetodoIndirectoCabeceraAbstracto',
        'name': '10. A. ESTADO DE FLUJOS DE EFECTIVO CONSOLIDADO (MÉTODO INDIRECTO) (NIIF ADOPTADAS)'
    }, { 
        'xbrl_element': 'ipp_ge:EstadoFlujosEfectivoConsolidadoMetodoIndirectoAbstracto',
        'name': 'Estado de Flujos de Efectivo Consolidado (Método Indirecto)'
    }, { 
        'xbrl_element': 'ipp_ge:I1435',
        'name': 'A) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE EXPLOTACIÓN (1 + 2 + 3 + 4)'
    }, { 
        'xbrl_element': 'ipp_ge:I1405',
        'name': '1. Resultado antes de impuestos'
    }, { 
        'xbrl_element': 'ipp_ge:I1410',
        'name': '2. Ajustes del resultado:'
    }, { 
        'xbrl_element': 'ipp_ge:I1411',
        'name': ' Amortización del inmovilizado'
    }, { 
        'xbrl_element': 'ipp_ge:I1412',
        'name': ' Otros ajustes del resultado (netos)'
    }, { 
        'xbrl_element': 'ipp_ge:I1415',
        'name': '3. Cambios en el capital corriente'
    }, { 
        'xbrl_element': 'ipp_ge:I1420',
        'name': '4. Otros flujos de efectivo de las actividades de explotación:'
    }, { 
        'xbrl_element': 'ipp_ge:I1421',
        'name': ' Pagos de intereses'
    }, { 
        'xbrl_element': 'ipp_ge:I1430',
        'name': ' Pagos por dividendos y remuneraciones de otros instrumentos de patrimonio'
    }, { 
        'xbrl_element': 'ipp_ge:I1422',
        'name': ' Cobros de dividendos'
    }, { 
        'xbrl_element': 'ipp_ge:I1423',
        'name': ' Cobros de intereses'
    }, { 
        'xbrl_element': 'ipp_ge:I1424',
        'name': ' Cobros/(Pagos) por impuesto sobre beneficios'
    }, { 
        'xbrl_element': 'ipp_ge:I1425',
        'name': ' Otros cobros/(pagos) de actividades de explotación'
    }, { 
        'xbrl_element': 'ipp_ge:I1460',
        'name': 'B) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE INVERSIÓN (1 + 2 + 3)'
    }, { 
        'xbrl_element': 'ipp_ge:I1440',
        'name': '1. Pagos por inversiones:'
    }, { 
        'xbrl_element': 'ipp_ge:I1441',
        'name': ' Empresas del grupo, asociadas y unidades de negocio'
    }, { 
        'xbrl_element': 'ipp_ge:I1442',
        'name': ' Inmovilizado material, intangible e inversiones inmobiliarias'
    }, { 
        'xbrl_element': 'ipp_ge:I1443',
        'name': ' Otros activos financieros'
    }, { 
        'xbrl_element': 'ipp_ge:I1444',
        'name': ' Otros activos'
    }, { 
        'xbrl_element': 'ipp_ge:I1450',
        'name': '2. Cobros por desinversiones:'
    }, { 
        'xbrl_element': 'ipp_ge:I1451',
        'name': ' Empresas del grupo, asociadas y unidades de negocio'
    }, { 
        'xbrl_element': 'ipp_ge:I1452',
        'name': ' Inmovilizado material, intangible e inversiones inmobiliarias'
    }, { 
        'xbrl_element': 'ipp_ge:I1453',
        'name': ' Otros activos financieros'
    }, { 
        'xbrl_element': 'ipp_ge:I1454',
        'name': ' Otros activos'
    }, { 
        'xbrl_element': 'ipp_ge:I1455',
        'name': '3. Otros flujos de efectivo de actividades de inversión'
    }, { 
        'xbrl_element': 'ipp_ge:I1456',
        'name': ' Cobros de dividendos'
    }, { 
        'xbrl_element': 'ipp_ge:I1457',
        'name': ' Cobros de intereses'
    }, { 
        'xbrl_element': 'ipp_ge:I1458',
        'name': ' Otros cobros/(pagos) de actividades de inversión'
    }, { 
        'xbrl_element': 'ipp_ge:I1490',
        'name': 'C) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE FINANCIACIÓN (1 + 2 + 3 + 4)'
    }, { 
        'xbrl_element': 'ipp_ge:I1470',
        'name': '1. Cobros y (pagos) por instrumentos de patrimonio:'
    }, { 
        'xbrl_element': 'ipp_ge:I1471',
        'name': ' Emisión'
    }, { 
        'xbrl_element': 'ipp_ge:I1472',
        'name': ' Amortización'
    }, { 
        'xbrl_element': 'ipp_ge:I1473',
        'name': ' Adquisición'
    }, { 
        'xbrl_element': 'ipp_ge:I1474',
        'name': ' Enajenación'
    }, { 
        'xbrl_element': 'ipp_ge:I1480',
        'name': '2. Cobros y (pagos) por instrumentos de pasivo financiero:'
    }, { 
        'xbrl_element': 'ipp_ge:I1481',
        'name': ' Emisión'
    }, { 
        'xbrl_element': 'ipp_ge:I1482',
        'name': ' Devolución y amortización'
    }, { 
        'xbrl_element': 'ipp_ge:I1485',
        'name': '3. Pagos por dividendos y remuneraciones de otros instrumentos de patrimonio'
    }, { 
        'xbrl_element': 'ipp_ge:I1486',
        'name': '4. Otros flujos de efectivo de actividades de financiación'
    }, { 
        'xbrl_element': 'ipp_ge:I1487',
        'name': ' Pagos de intereses'
    }, { 
        'xbrl_element': 'ipp_ge:I1488',
        'name': ' Otros cobros/(pagos) de actividades de financiación'
    }, { 
        'xbrl_element': 'ipp_ge:I1492',
        'name': 'D) EFECTO DE LAS VARIACIONES DE LOS TIPOS DE CAMBIO'
    }, { 
        'xbrl_element': 'ipp_ge:I1495',
        'name': 'E) AUMENTO/(DISMINUCIÓN) NETO DE EFECTIVO Y EQUIVALENTES (A + B + C + D)'
    }, { 
        'xbrl_element': 'ipp_ge:I1499',
        'name': 'F) EFECTIVO Y EQUIVALENTES AL INICIO DEL PERÍODO'
    }, { 
        'xbrl_element': 'ipp_ge:I1500',
        'name': 'G) EFECTIVO Y EQUIVALENTES AL FINAL DEL PERÍODO (E + F)'
    }, { 
        'xbrl_element': 'ipp_ge:EstadoFlujosEfectivoConsolidadoMetodoIndirectoComponentesEfectivo',
        'name': 'COMPONENTES DEL EFECTIVO Y EQUIVALENTES AL FINAL DEL PERIODO'
    }, { 
        'xbrl_element': 'ipp_ge:I1550',
        'name': ' Caja y bancos'
    }, { 
        'xbrl_element': 'ipp_ge:I1552',
        'name': ' Otros activos financieros'
    }, { 
        'xbrl_element': 'ipp_ge:I1553',
        'name': ' Menos: Descubiertos bancarios reintegrables a la vista'
    }, { 
        'xbrl_element': 'ipp_ge:I1600',
        'name': 'TOTAL EFECTIVO Y EQUIVALENTES AL FINAL DEL PERIODO'
    }]
    root = FinancialConcept(name='Flujo de caja consolidado', xbrl_element='ipp_ge:EstadoFlujosEfectivoConsolidadoMetodoIndirectoLineaElementos',
        taxonomy='http://www.cnmv.es/ipp-ge/2016')
    root.save()
    root.parent = root
    root.save()
    for concept in concepts:
        FinancialConcept(name=concept['name'], xbrl_element=concept['xbrl_element'], parent=root, taxonomy=root.taxonomy).save()

    concepts = [{
        'xbrl_element': 'ipp_en:I1800',
        'name': 'A) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE EXPLOTACIÓN (1 + 2 + 3 + 4 + 5)'
    }, { 
        'xbrl_element': 'ipp_en:I1810',
        'name': '1. Resultado del periodo'
    }, { 
        'xbrl_element': 'ipp_en:I1820',
        'name': '2. Ajustes para obtener los flujos de efectivo de las actividades de explotación:'
    }, { 
        'xbrl_element': 'ipp_en:I1821',
        'name': ' Amortización'
    }, { 
        'xbrl_element': 'ipp_en:I1822',
        'name': ' Otros ajustes'
    }, { 
        'xbrl_element': 'ipp_en:I1830',
        'name': '3. Aumento/(disminución) neto de los activos de explotación:'
    }, { 
        'xbrl_element': 'ipp_en:I1831',
        'name': ' Activos financieros mantenidos para negociar '
    }, { 
        'xbrl_element': 'ipp_en:I1832',
        'name': ' Activos financieros designados a valor razonable con cambios en resultados'
    }, { 
        'xbrl_element': 'ipp_en:I1833',
        'name': ' Activos financieros disponibles para la venta'
    }, { 
        'xbrl_element': 'ipp_en:I1834',
        'name': ' Préstamos y partidas a cobrar'
    }, { 
        'xbrl_element': 'ipp_en:I1835',
        'name': ' Otros activos de explotación'
    }, { 
        'xbrl_element': 'ipp_en:I1840',
        'name': '4. Aumento/(disminución) neto de los pasivos de explotación:'
    }, { 
        'xbrl_element': 'ipp_en:I1841',
        'name': ' Pasivos financieros mantenidos para negociar '
    }, { 
        'xbrl_element': 'ipp_en:I1842',
        'name': ' Pasivos financieros designados a valor razonable con cambios en resultados'
    }, { 
        'xbrl_element': 'ipp_en:I1843',
        'name': ' Pasivos financieros a coste amortizado '
    }, { 
        'xbrl_element': 'ipp_en:I1844',
        'name': ' Otros pasivos de explotación'
    }, { 
        'xbrl_element': 'ipp_en:I1850',
        'name': '5. Cobros/(Pagos) por impuesto sobre las ganancias'
    }, { 
        'xbrl_element': 'ipp_en:I1860',
        'name': 'B) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE INVERSIÓN (1 + 2)'
    }, { 
        'xbrl_element': 'ipp_en:I1870',
        'name': '1. Pagos:'
    }, { 
        'xbrl_element': 'ipp_en:I1871',
        'name': ' Activos tangibles'
    }, { 
        'xbrl_element': 'ipp_en:I1872',
        'name': ' Activos intangibles'
    }, { 
        'xbrl_element': 'ipp_en:I1873',
        'name': ' Inversiones en negocios conjuntos y asociadas'
    }, { 
        'xbrl_element': 'ipp_en:I1874',
        'name': ' Entidades dependientes y otras unidades de negocio'
    }, { 
        'xbrl_element': 'ipp_en:I1875',
        'name': ' Activos no corrientes y pasivos que se han clasificado como mantenidos para la venta'
    }, { 
        'xbrl_element': 'ipp_en:I1876',
        'name': ' Inversiones mantenidas hasta el vencimiento'
    }, { 
        'xbrl_element': 'ipp_en:I1877',
        'name': ' Otros pagos relacionados con actividades de inversión'
    }, { 
        'xbrl_element': 'ipp_en:I1880',
        'name': '2. Cobros:'
    }, { 
        'xbrl_element': 'ipp_en:I1881',
        'name': ' Activos tangibles'
    }, { 
        'xbrl_element': 'ipp_en:I1882',
        'name': ' Activos intangibles'
    }, { 
        'xbrl_element': 'ipp_en:I1883',
        'name': ' Inversiones en negocios conjuntos y asociadas'
    }, { 
        'xbrl_element': 'ipp_en:I1884',
        'name': ' Entidades dependientes y otras unidades de negocio'
    }, { 
        'xbrl_element': 'ipp_en:I1885',
        'name': ' Activos no corrientes y pasivos que se han clasificado como mantenidos para la venta'
    }, { 
        'xbrl_element': 'ipp_en:I1886',
        'name': ' Inversiones mantenidas hasta el vencimiento'
    }, { 
        'xbrl_element': 'ipp_en:I1887',
        'name': ' Otros cobros relacionados con actividades de inversión'
    }, { 
        'xbrl_element': 'ipp_en:I1890',
        'name': 'C) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE FINANCIACIÓN (1 + 2)'
    }, { 
        'xbrl_element': 'ipp_en:I1900',
        'name': '1. Pagos:'
    }, { 
        'xbrl_element': 'ipp_en:I1901',
        'name': ' Dividendos'
    }, { 
        'xbrl_element': 'ipp_en:I1902',
        'name': ' Pasivos subordinados'
    }, { 
        'xbrl_element': 'ipp_en:I1903',
        'name': ' Amortización de instrumentos de patrimonio propio'
    }, { 
        'xbrl_element': 'ipp_en:I1904',
        'name': ' Adquisición de instrumentos de patrimonio propio'
    }, { 
        'xbrl_element': 'ipp_en:I1905',
        'name': ' Otros pagos relacionados con actividades de financiación'
    }, { 
        'xbrl_element': 'ipp_en:I1910',
        'name': '2. Cobros:'
    }, { 
        'xbrl_element': 'ipp_en:I1911',
        'name': ' Pasivos subordinados'
    }, { 
        'xbrl_element': 'ipp_en:I1912',
        'name': ' Emisión de instrumentos de patrimonio propio'
    }, { 
        'xbrl_element': 'ipp_en:I1913',
        'name': ' Enajenación de instrumentos de patrimonio propio'
    }, { 
        'xbrl_element': 'ipp_en:I1914',
        'name': ' Otros cobros relacionados con actividades de financiación'
    }, { 
        'xbrl_element': 'ipp_en:I1920',
        'name': 'D) EFECTO DE LAS VARIACIONES DE LOS TIPOS DE CAMBIO '
    }, { 
        'xbrl_element': 'ipp_en:I1930',
        'name': 'E) AUMENTO/(DISMINUCIÓN) NETO DEL EFECTIVO Y EQUIVALENTES (A + B + C + D)'
    }, { 
        'xbrl_element': 'ipp_en:I1940',
        'name': 'F) EFECTIVO Y EQUIVALENTES AL INICIO DEL PERÍODO'
    }, { 
        'xbrl_element': 'ipp_en:I1950',
        'name': 'G) EFECTIVO Y EQUIVALENTES AL FINAL DEL PERÍODO (E + F)'
    }, { 
        'xbrl_element': 'ipp_en:EstadoFlujosEfectivoConsolidadoMetodoIndirectoComponentesEfectivo',
        'name': 'COMPONENTES DEL EFECTIVO Y EQUIVALENTES AL FINAL DEL PERIODO'
    }, { 
        'xbrl_element': 'ipp_en:I1955',
        'name': ' Efectivo'
    }, { 
        'xbrl_element': 'ipp_en:I1960',
        'name': ' Saldos equivalentes al efectivo en bancos centrales'
    }, { 
        'xbrl_element': 'ipp_en:I1965',
        'name': ' Otros activos financieros '
    }, { 
        'xbrl_element': 'ipp_en:I1970',
        'name': ' Menos: Descubiertos bancarios reintegrables a la vista'
    }, { 
        'xbrl_element': 'ipp_en:I1980',
        'name': 'TOTAL EFECTIVO Y EQUIVALENTES AL FINAL DEL PERIODO'
    }, { 
        'xbrl_element': 'ipp_en:I1990',
        'name': 'Del cual: en poder de entidades del grupo pero no disponible por el grupo'
    }]
    root = FinancialConcept(name='Flujo de caja consolidado', xbrl_element='ipp_en:EstadoFlujosEfectivoConsolidadoMetodoIndirectoLineaElementos',
        taxonomy='http://www.cnmv.es/ipp-en/2016')
    root.save()
    root.parent = root
    root.save()
    for concept in concepts:
        FinancialConcept(name=concept['name'], xbrl_element=concept['xbrl_element'], parent=root, taxonomy=root.taxonomy).save()

    concepts = [{
        'xbrl_element': 'ipp_se:I8435',
        'name': 'A) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE EXPLOTACIÓN (1 + 2 + 3)'
    }, {
        'xbrl_element': 'ipp_se:I8405',
        'name': '1. Actividad aseguradora:'
    }, { 
        'xbrl_element': 'ipp_se:I8406',
        'name': ' Cobros en efectivo de la actividad aseguradora'
    }, { 
        'xbrl_element': 'ipp_se:I8407',
        'name': ' Pagos en efectivo de la actividad aseguradora'
    }, { 
        'xbrl_element': 'ipp_se:I8410',
        'name': '2. Otras actividades de explotación:'
    }, { 
        'xbrl_element': 'ipp_se:I8415',
        'name': ' Cobros en efectivo de otras actividades de explotación'
    }, { 
        'xbrl_element': 'ipp_se:I8416',
        'name': ' Pagos en efectivo de otras actividades de explotación'
    }, { 
        'xbrl_element': 'ipp_se:I8425',
        'name': '3. Cobros/(pagos) por impuesto sobre beneficios'
    }, { 
        'xbrl_element': 'ipp_se:I8460',
        'name': 'B) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE INVERSIÓN (1 + 2)'
    }, { 
        'xbrl_element': 'ipp_se:I8450',
        'name': '1. Cobros de actividades de inversión:'
    }, { 
        'xbrl_element': 'ipp_se:I8451',
        'name': ' Inmovilizado material'
    }, { 
        'xbrl_element': 'ipp_se:I8452',
        'name': ' Inversiones inmobiliarias'
    }, { 
        'xbrl_element': 'ipp_se:I8453',
        'name': ' Inmovilizado intangible'
    }, { 
        'xbrl_element': 'ipp_se:I8454',
        'name': ' Instrumentos financieros'
    }, { 
        'xbrl_element': 'ipp_se:I8455',
        'name': ' Participaciones'
    }, { 
        'xbrl_element': 'ipp_se:I8457',
        'name': ' Entidades dependientes y otras unidades de negocio'
    }, { 
        'xbrl_element': 'ipp_se:I8456',
        'name': ' Intereses cobrados'
    }, { 
        'xbrl_element': 'ipp_se:I8459',
        'name': ' Dividendos cobrados'
    }, { 
        'xbrl_element': 'ipp_se:I8458',
        'name': ' Otros cobros relacionados con actividades de inversión'
    }, { 
        'xbrl_element': 'ipp_se:I8440',
        'name': '2. Pagos de actividades de inversión:'
    }, { 
        'xbrl_element': 'ipp_se:I8441',
        'name': ' Inmovilizado material'
    }, { 
        'xbrl_element': 'ipp_se:I8442',
        'name': ' Inversiones inmobiliarias'
    }, { 
        'xbrl_element': 'ipp_se:I8443',
        'name': ' Inmovilizado intangible'
    }, { 
        'xbrl_element': 'ipp_se:I8444',
        'name': ' Instrumentos financieros'
    }, { 
        'xbrl_element': 'ipp_se:I8445',
        'name': ' Participaciones'
    }, { 
        'xbrl_element': 'ipp_se:I8447',
        'name': ' Entidades dependientes y otras unidades de negocio'
    }, { 
        'xbrl_element': 'ipp_se:I8448',
        'name': ' Otros pagos relacionados con actividades de inversión'
    }, { 
        'xbrl_element': 'ipp_se:I8490',
        'name': 'C) FLUJOS DE EFECTIVO DE LAS ACTIVIDADES DE FINANCIACIÓN (1 + 2)'
    }, { 
        'xbrl_element': 'ipp_se:I8480',
        'name': '1. Cobros de actividades de financiación:'
    }, { 
        'xbrl_element': 'ipp_se:I8481',
        'name': ' Pasivos subordinados'
    }, { 
        'xbrl_element': 'ipp_se:I8482',
        'name': ' Cobros por emisión de instrumentos de patrimonio y ampliación de capital'
    }, { 
        'xbrl_element': 'ipp_se:I8483',
        'name': ' Derramas activas y aportaciones de los socios o mutualistas'
    }, { 
        'xbrl_element': 'ipp_se:I8485',
        'name': ' Enajenación de valores propios'
    }, { 
        'xbrl_element': 'ipp_se:I8486',
        'name': ' Otros cobros relacionados con actividades de financiación'
    }, { 
        'xbrl_element': 'ipp_se:I8470',
        'name': '2. Pagos de actividades de financiación:'
    }, { 
        'xbrl_element': 'ipp_se:I8471',
        'name': ' Dividendos a los accionistas'
    }, { 
        'xbrl_element': 'ipp_se:I8475',
        'name': ' Intereses pagados'
    }, { 
        'xbrl_element': 'ipp_se:I8472',
        'name': ' Pasivos subordinados'
    }, { 
        'xbrl_element': 'ipp_se:I8473',
        'name': ' Pagos por devolución de aportaciones a los accionistas'
    }, { 
        'xbrl_element': 'ipp_se:I8474',
        'name': ' Derramas pasivas y devolución de aportaciones a los socios o mutualistas'
    }, { 
        'xbrl_element': 'ipp_se:I8477',
        'name': ' Adquisición de valores propios'
    }, { 
        'xbrl_element': 'ipp_se:I8478',
        'name': ' Otros pagos relacionados con actividades de financiación'
    }, { 
        'xbrl_element': 'ipp_se:I8492',
        'name': 'D) EFECTO DE LAS VARIACIONES DE LOS TIPOS DE CAMBIO'
    }, { 
        'xbrl_element': 'ipp_se:I8495',
        'name': 'E) AUMENTO/(DISMINUCIÓN) NETO DE EFECTIVO Y EQUIVALENTES (A + B + C + D)'
    }, { 
        'xbrl_element': 'ipp_se:I8499',
        'name': 'F) EFECTIVO Y EQUIVALENTES AL INICIO DEL PERÍODO'
    }, { 
        'xbrl_element': 'ipp_se:I8500',
        'name': 'G) EFECTIVO Y EQUIVALENTES AL FINAL DEL PERÍODO (E + F)'
    }, { 
        'xbrl_element': 'ipp_se:EstadoFlujosEfectivoConsolidadoMetodoDirectoComponentesEfectivo',
        'name': 'COMPONENTES DEL EFECTIVO Y EQUIVALENTES AL FINAL DEL PERIODO'
    }, { 
        'xbrl_element': 'ipp_se:I8550',
        'name': ' Caja y bancos'
    }, { 
        'xbrl_element': 'ipp_se:I8552',
        'name': ' Otros activos financieros'
    }, { 
        'xbrl_element': 'ipp_se:I8553',
        'name': ' Menos: Descubiertos bancarios reintegrables a la vista'
    }, { 
        'xbrl_element': 'ipp_se:I8600',
        'name': 'TOTAL EFECTIVO Y EQUIVALENTES DE EFECTIVO AL FINAL DEL PERIODO'
    }]
    root = FinancialConcept(name='Flujo de caja consolidado', xbrl_element='ipp_se:EstadoFlujosEfectivoConsolidadoMetodoIndirectoLineaElementos',
        taxonomy='http://www.cnmv.es/ipp-en/2016')
    root.save()
    root.parent = root
    root.save()
    for concept in concepts:
        FinancialConcept(name=concept['name'], xbrl_element=concept['xbrl_element'], parent=root, taxonomy=root.taxonomy).save()

def rollback(apps, schema_editor):
    root = FinancialConcept.objects.get(xbrl_element='ipp-gen:EstadoFlujosEfectivoConsolidadoMetodoIndirecto')
    FinancialConcept.objects.filter(parent=root).delete()
    root.delete()

    root = FinancialConcept.objects.get(xbrl_element='ipp-enc:EstadoFlujosEfectivoConsolidadoMetodoIndirecto')
    FinancialConcept.objects.filter(parent=root).delete()
    root.delete()

    root = FinancialConcept.objects.get(xbrl_element='ipp-seg:EstadoFlujosEfectivoConsolidadoMetodoIndirecto')
    FinancialConcept.objects.filter(parent=root).delete()
    root.delete()

    root = FinancialConcept.objects.get(xbrl_element='ipp_ge:EstadoFlujosEfectivoConsolidadoMetodoIndirectoLineaElementos')
    FinancialConcept.objects.filter(parent=root).delete()
    root.delete()

    root = FinancialConcept.objects.get(xbrl_element='ipp_en:EstadoFlujosEfectivoConsolidadoMetodoIndirectoLineaElementos')
    FinancialConcept.objects.filter(parent=root).delete()
    root.delete()

    root = FinancialConcept.objects.get(xbrl_element='ipp_se:EstadoFlujosEfectivoConsolidadoMetodoIndirectoLineaElementos')
    FinancialConcept.objects.filter(parent=root).delete()
    root.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20170919_1554'),
    ]

    operations = [
        migrations.RunPython(insertData, rollback),
    ]
